/**
 * PostgreSQL Schema (opt-in backend)
 *
 * This is the PostgreSQL equivalent of `schema.sql` PLUS every migration in
 * `migrations.ts` folded in (the PG backend ships the latest schema directly,
 * it does not replay the SQLite migration chain). The worker applies this once
 * on connect; it is fully idempotent (`IF NOT EXISTS` everywhere) so re-opening
 * an existing database is a no-op.
 *
 * Full-text search is implemented to behave CONSISTENTLY with the SQLite FTS5
 * path in `queries.ts`:
 *   - a `tsv tsvector` column maintained by a trigger (the PG-idiomatic
 *     equivalent of the `nodes_fts` virtual table + sync triggers);
 *   - the `simple` text-search configuration (NOT `english`) so code
 *     identifiers like `getUserById` tokenize predictably instead of being
 *     stemmed/stop-worded, matching FTS5's plain tokenizer;
 *   - `setweight` column labels A/B/C/D mapped to the same relative importance
 *     as the FTS5 `bm25(nodes_fts, 0, 20, 5, 1, 2)` weights
 *     (name=A, qualified_name=B, signature=C, docstring=D). The query layer
 *     ranks with `ts_rank('{0.05,0.1,0.25,1.0}', ...)` — the 1:2:5:20 ratio
 *     normalized to D,C,B,A — so name matches dominate exactly as under bm25.
 *
 * `SEEDED_SCHEMA_VERSION` is imported from `migrations.ts` (single source of
 * truth — it can't drift). The worker seeds `schema_versions` with this value
 * so `getCurrentVersion()` reports the latest version and the SQLite migration
 * runner finds nothing pending. NOTE: when bumping `CURRENT_SCHEMA_VERSION`,
 * fold the new migration's DDL into `PG_SCHEMA` below — the version seed makes
 * the runner skip it, so the PG schema must already include it.
 */

import { CURRENT_SCHEMA_VERSION } from './migrations';

export const SEEDED_SCHEMA_VERSION = CURRENT_SCHEMA_VERSION;

export const PG_SCHEMA = `
-- Schema version tracking
CREATE TABLE IF NOT EXISTS schema_versions (
    version INTEGER PRIMARY KEY,
    applied_at BIGINT NOT NULL,
    description TEXT
);

-- =============================================================================
-- Core Tables
-- =============================================================================

CREATE TABLE IF NOT EXISTS nodes (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    qualified_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    language TEXT NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    start_column INTEGER NOT NULL,
    end_column INTEGER NOT NULL,
    docstring TEXT,
    signature TEXT,
    visibility TEXT,
    is_exported INTEGER DEFAULT 0,
    is_async INTEGER DEFAULT 0,
    is_static INTEGER DEFAULT 0,
    is_abstract INTEGER DEFAULT 0,
    decorators TEXT,
    type_parameters TEXT,
    return_type TEXT,
    updated_at BIGINT NOT NULL,
    tsv tsvector
);

CREATE TABLE IF NOT EXISTS edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    target TEXT NOT NULL,
    kind TEXT NOT NULL,
    metadata TEXT,
    line INTEGER,
    col INTEGER,
    provenance TEXT DEFAULT NULL,
    FOREIGN KEY (source) REFERENCES nodes(id) ON DELETE CASCADE,
    FOREIGN KEY (target) REFERENCES nodes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS files (
    path TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    language TEXT NOT NULL,
    size BIGINT NOT NULL,
    -- DOUBLE PRECISION, not BIGINT: callers bind fs.Stats.mtimeMs, which is a
    -- FRACTIONAL millisecond float on ns-precision filesystems. SQLite's type
    -- affinity stores the float silently; PG's int8 input parser would reject
    -- it ('invalid input syntax for type bigint: "...123.456"') and break
    -- every file upsert. float8 carries the same 53-bit precision as the JS
    -- number, and the staleness check compares Math.floor()ed values.
    modified_at DOUBLE PRECISION NOT NULL,
    indexed_at BIGINT NOT NULL,
    node_count INTEGER DEFAULT 0,
    errors TEXT
);

CREATE TABLE IF NOT EXISTS unresolved_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_node_id TEXT NOT NULL,
    reference_name TEXT NOT NULL,
    reference_kind TEXT NOT NULL,
    line INTEGER NOT NULL,
    col INTEGER NOT NULL,
    candidates TEXT,
    file_path TEXT NOT NULL DEFAULT '',
    language TEXT NOT NULL DEFAULT 'unknown',
    FOREIGN KEY (from_node_id) REFERENCES nodes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- =============================================================================
-- Full-text search (consistent with SQLite FTS5 path)
-- =============================================================================

-- Build the weighted tsvector exactly mirroring the FTS5 bm25 column weights:
-- name=A(20), qualified_name=B(5), signature=C(2), docstring=D(1).
-- 'simple' config => no stemming/stop-words => code identifiers stay intact.
CREATE OR REPLACE FUNCTION codegraph_nodes_tsv() RETURNS trigger AS $codegraph$
BEGIN
    NEW.tsv :=
        setweight(to_tsvector('simple', coalesce(NEW.name, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(NEW.qualified_name, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(NEW.signature, '')), 'C') ||
        setweight(to_tsvector('simple', coalesce(NEW.docstring, '')), 'D');
    RETURN NEW;
END
$codegraph$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS nodes_tsv_trg ON nodes;
CREATE TRIGGER nodes_tsv_trg
    BEFORE INSERT OR UPDATE OF name, qualified_name, signature, docstring
    ON nodes FOR EACH ROW
    EXECUTE FUNCTION codegraph_nodes_tsv();

-- =============================================================================
-- Indexes
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_nodes_kind ON nodes(kind);
CREATE INDEX IF NOT EXISTS idx_nodes_name ON nodes(name);
CREATE INDEX IF NOT EXISTS idx_nodes_qualified_name ON nodes(qualified_name);
CREATE INDEX IF NOT EXISTS idx_nodes_file_path ON nodes(file_path);
CREATE INDEX IF NOT EXISTS idx_nodes_language ON nodes(language);
CREATE INDEX IF NOT EXISTS idx_nodes_file_line ON nodes(file_path, start_line);
CREATE INDEX IF NOT EXISTS idx_nodes_lower_name ON nodes(lower(name));
CREATE INDEX IF NOT EXISTS idx_nodes_tsv ON nodes USING GIN(tsv);

CREATE INDEX IF NOT EXISTS idx_edges_kind ON edges(kind);
CREATE INDEX IF NOT EXISTS idx_edges_source_kind ON edges(source, kind);
CREATE INDEX IF NOT EXISTS idx_edges_target_kind ON edges(target, kind);
CREATE INDEX IF NOT EXISTS idx_edges_provenance ON edges(provenance);

CREATE INDEX IF NOT EXISTS idx_files_language ON files(language);
CREATE INDEX IF NOT EXISTS idx_files_modified_at ON files(modified_at);

CREATE INDEX IF NOT EXISTS idx_unresolved_from_node ON unresolved_refs(from_node_id);
CREATE INDEX IF NOT EXISTS idx_unresolved_name ON unresolved_refs(reference_name);
CREATE INDEX IF NOT EXISTS idx_unresolved_file_path ON unresolved_refs(file_path);
CREATE INDEX IF NOT EXISTS idx_unresolved_from_name ON unresolved_refs(from_node_id, reference_name);

-- Seed schema version so the SQLite migration runner sees nothing pending.
INSERT INTO schema_versions (version, applied_at, description)
VALUES (${SEEDED_SCHEMA_VERSION}, (extract(epoch from now()) * 1000)::bigint, 'PostgreSQL schema (all migrations folded in)')
ON CONFLICT (version) DO NOTHING;
`;
